version: '3'

services:
  next-app:
    container_name: tova.fi-dev
    build:
      context: ./tova.fi
      dockerfile: dev.Dockerfile

    environment:
      LASTFM_USER: tokeeee
      LASTFM_APIKEY: ${LASTFM_APIKEY}
      
    env_file:
      - .env
    volumes:
      - ./tova.fi/public:/app/public
      - ./tova.fi/lib:/app/lib
      - ./tova.fi/styles:/app/styles
      - ./tova.fi/pages:/app/pages
    restart: always
    ports:
      - 3000:3000
